# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np
np.zeros(10,dtype=("int32"))



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

2. Create a null vector of size 10 

In [5]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a vector with values ranging from 10 to 49

In [7]:
import numpy as np
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [8]:
arr.shape

(40,)

5. Print the type of the previous array in question 3

In [12]:
type(arr)

numpy.ndarray

6. Print the numpy version and the configuration


In [7]:
import numpy as np
print(np.version.version)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Classic/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Classic/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Classic/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows

7. Print the dimension of the array in question 3


In [2]:
import numpy as np
arr=np.arange(10,50)
arr.ndim

1

8. Create a boolean array with all the True values

In [5]:
import numpy as np
arr=np.ones(12,dtype=bool)
arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

9. Create a two dimensional array




In [7]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
a.ndim

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


2

10. Create a three dimensional array



In [11]:
import numpy as np
a=np.array([[[1,2,3],[3,4,5],[6,7,8]]])
print(a)
a.ndim

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [13]:
import numpy as np
a=np.arange(10)
print(a)
np.flip(a)

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [20]:
import numpy as np
a=np.zeros(10,dtype=("int32"))
print(a)
print("update")
a[5]=1
print(a)

[0 0 0 0 0 0 0 0 0 0]
update
[0 0 0 0 0 1 0 0 0 0]


13. Create a 3x3 identity matrix

In [23]:
import numpy as np
a=np.identity(3,dtype=("int32"))
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,],dtype=("float32"))
arr

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [25]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[0,4,1],[7,2,12]])
arr1*arr2

array([[ 0,  8,  3],
       [28, 10, 72]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [29]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
arr2=np.array([[0,4,1],[7,2,12]])
print(arr2)
arr1==arr2

[[1 2 3]
 [4 5 6]]
[[ 0  4  1]
 [ 7  2 12]]


array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [31]:
import numpy as np
a=np.arange(10)
a[a%2==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [60]:
import numpy as np
a=np.arange(10)
p=a[a%2==1 ]
print(p)
p[0:6]=-1
p




[1 3 5 7 9]


array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [61]:
import numpy as np
arr=np.arange(10)
print(arr)
arr[5:8]=12
arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [67]:
import numpy as np
a=np.ones((4,4),dtype=("int32"))
print(a)
a[1:-1,1:-1]=0
a

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [72]:
import numpy as np
arr2d=np.arange(1,10).reshape(3,3)
print(arr2d)
arr2d[1][1]=12
arr2d

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [74]:
arr3d=np.arange(1,13).reshape(2,2,3)
print(arr3d)
arr3d[0]=64
arr3d

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [81]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a)
p=a[0]
p

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [83]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a)
p=a[1][1]
p

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [11]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a)
p=a[:2,3]
p


[[0 1 2 3 4]
 [5 6 7 8 9]]


array([3, 8])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
import numpy as np
a=np.random.randn(10,10)
print(a)
print(a.min())
print(a.max())

[[-0.74431084 -0.09812438 -0.18981296 -0.28041316 -0.65177033 -0.13022008
   0.47459077 -0.37938411  0.25428471 -0.29072941]
 [ 2.10625894 -0.17369494 -1.48126963 -1.96385893 -0.68500448  0.36343468
   0.95534695 -1.00238278 -1.1177268  -0.266723  ]
 [ 0.96854104 -0.38073688  0.08673422 -0.41180444 -1.31662967  0.21791435
   0.36277633  0.3795072  -0.07268786  1.41382753]
 [-1.29553693 -0.5496647  -0.78395279 -0.43109002  1.12199377 -0.22232069
   1.33400512 -0.44824593  1.577207    1.14970137]
 [-0.05390056 -0.29498951 -0.95118768 -1.10589888 -0.38989807  0.19292246
   0.57408508 -0.00660134 -0.09177903 -1.03065234]
 [-0.16650894 -0.44974623 -0.08764735 -0.13212831 -1.17433208 -1.5119618
   0.65027375 -0.78525954 -0.89824468  0.78064129]
 [ 0.16455322  0.26762927  0.56004719 -0.86912119  1.60467962 -1.19375741
  -0.61799783  1.0537072  -1.82912241  0.10987449]
 [ 0.41000563  0.38338224  0.05421294  1.18237271 -0.88710261  0.18463775
  -1.25600114  0.1784142  -0.13615478 -0.20567879]
 

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [32]:
import numpy as np

x=np.intersect1d([1,2,3,2,3,4,3,4,5,6],[7,2,10,2,7,4,9,4,9,8])

x

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [33]:
import numpy as np 
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [42]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print(names)
print(data)
print(names != 'Will')
data[names !=' Will']

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.78418994  0.06531904 -1.67745655 -0.6003727 ]
 [-3.35592845  1.107218    0.51781638  0.37819923]
 [ 0.17797298 -1.49208306  0.4692376  -0.81002492]
 [ 0.70823926 -0.09799798 -2.30669212  0.51397306]
 [-1.10727556  0.51145656  1.34882457  0.18001126]
 [ 1.08196364 -0.71895026  1.41701739  1.7817248 ]
 [-0.61857966  1.46417983 -0.17821146  0.23785573]]
[ True  True False  True False  True  True]


array([[-0.78418994,  0.06531904, -1.67745655, -0.6003727 ],
       [-3.35592845,  1.107218  ,  0.51781638,  0.37819923],
       [ 0.17797298, -1.49208306,  0.4692376 , -0.81002492],
       [ 0.70823926, -0.09799798, -2.30669212,  0.51397306],
       [-1.10727556,  0.51145656,  1.34882457,  0.18001126],
       [ 1.08196364, -0.71895026,  1.41701739,  1.7817248 ],
       [-0.61857966,  1.46417983, -0.17821146,  0.23785573]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [2]:
import numpy as np
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print(names)
print(data)
mask=(names != 'Will')&(names != 'Joe')
print(mask)
data[mask]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-4.06216442e-01  4.47780607e-01 -1.64552756e+00 -3.12657007e-01]
 [ 1.81011400e+00 -1.00033054e+00 -5.72548213e-04  2.01817835e+00]
 [-2.44283800e-01 -2.51935979e+00  1.03583792e+00  1.33723801e+00]
 [ 1.53972181e+00 -6.23525752e-02  2.22046243e+00  3.24676955e-01]
 [-7.58718331e-01  1.27392317e+00  8.92520406e-02 -5.09485598e-02]
 [ 9.19952767e-01 -1.51714557e+00  1.49529082e+00  9.76663365e-02]
 [ 8.00246277e-01  1.25006107e-01  1.77315408e+00  6.79371910e-02]]
[ True False False  True False False False]


array([[-0.40621644,  0.44778061, -1.64552756, -0.31265701],
       [ 1.53972181, -0.06235258,  2.22046243,  0.32467695]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [10]:
import numpy as np
a=np.arange(1,16,dtype=np.float64).reshape(5,3)
print(a)


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [11]:
import numpy as np
a=np.arange(1,17,dtype=("float32")).reshape(2,2,4)
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float32)

33. Swap axes of the array you created in Question 32

In [19]:
import numpy as np
a=np.arange(1,17,dtype=("float32")).reshape(2,2,4)
print(a)
a.swapaxes(0,1)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


array([[[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]],

       [[ 5.,  6.,  7.,  8.],
        [13., 14., 15., 16.]]], dtype=float32)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [29]:
import numpy as np
a=np.arange(10)
print(a)
sq=a**0.5
print(sq)
np.where(sq<0.5,0,sq)




[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [30]:
import numpy as np
a=np.random.randn(12)
b=np.random.randn(12)
print(a)
print(b)
np.maximum(a,b)

[ 0.47961173  0.12735924  1.14072845 -0.85853451  0.38761009 -0.27269579
 -0.52137789 -1.11778334  1.28670523  0.3748508  -0.09527719 -1.83087131]
[ 0.19396868 -1.38110903 -0.60832914 -0.4852132  -1.64401685  0.46957066
 -0.62381178  0.26302964 -1.0860784   0.53450082 -0.14870174 -0.21769307]


array([ 0.47961173,  0.12735924,  1.14072845, -0.4852132 ,  0.38761009,
        0.46957066, -0.52137789,  0.26302964,  1.28670523,  0.53450082,
       -0.09527719, -0.21769307])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [37]:
import numpy as np
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
print(names)

print(np.unique(names))

print(np.sort(names))

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
['Bob' 'Joe' 'Will']
['Bob' 'Bob' 'Joe' 'Joe' 'Joe' 'Will' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [46]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
print(a)
print(b)
a[~np.in1d(a,b)]

[1 2 3 4 5]
[5 6 7 8 9]


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [65]:
import numpy as np
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn=np.array([[10,10,10]])
print(newColumn)
sampleArray2=np.delete(sampleArray,1,1)
print(sampleArray2)
sampleArray2=np.insert(sampleArray2,1,newColumn,axis=1)
sampleArray2

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[10 10 10]]
[[34 73]
 [82 12]
 [53 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [67]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)
y=np.array([[6,23],[-1,7],[8,9]])
print(y)
np.dot(x,y)

[[1 2 3]
 [4 5 6]]
[[ 6 23]
 [-1  7]
 [ 8  9]]


array([[ 28,  64],
       [ 67, 181]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [69]:
import numpy as np
a=np.random.randn(20)
print(a)
a.cumsum()


[ 0.4855944  -0.51338049  0.48435664  0.14510117 -1.15152643 -1.01947976
 -0.60654468  1.08041443  0.63663139 -0.52027812  0.59826078 -1.12519015
 -0.30941909 -0.34917783  1.30971322 -0.49919451 -0.20138781 -1.54871079
  0.24895486  1.4195988 ]


array([ 0.4855944 , -0.02778609,  0.45657055,  0.60167172, -0.54985471,
       -1.56933447, -2.17587915, -1.09546472, -0.45883333, -0.97911144,
       -0.38085067, -1.50604081, -1.8154599 , -2.16463773, -0.85492451,
       -1.35411902, -1.55550684, -3.10421762, -2.85526277, -1.43566397])